### PR TITLE
Fixed the 403 error code being shown to the console as the 401 error

### PR DESCRIPTION
**Pull request by Tresquel**

### CODE REVIEW

**Comment by Tresquel** [comment]
This contributor license applies to MSC Mod Loader Pro project.

# MSC Mod Loader Pro Contributor Agreement

1. You, the contributor, grant us permission to use your code in any fashion in the scope of MSC Mod Loader Pro project.
2. While you get credited for your work, you may not demand any additional rights or obligations to your contribution.
3. To signify Agreement, Check the box below and type your (user)name.

[x] Tresquel
___________

**Comment by Tresquel** [comment]
how do i do it?

**Comment by Tresquel** [comment]
[x] Tresquel

**Comment by Tresquel** [comment]
MSC Mod Loader Pro Contributor Agreement
You, the contributor, grant us permission to use your code in any fashion in the scope of MSC Mod Loader Pro project.
While you get credited for your work, you may not demand any additional rights or obligations to your contribution.
To signify Agreement, Check the box below and type your (user)name.
[x] Tresquel

**Comment by Tresquel** [comment]
> Hi, welcome to MSC Mod Loader Pro project! We require contributors to sign [Contributor License Agreement](https://github.com/MSCLoaderPro/MSCModLoaderPro/blob/main/CONTRIBUTOR_LICENSE.md) before we can review and merge your code. In order to start, please read the text from the link, copy the text of agreement, sign it and post it here. For any questions, please contact @Athlon007.

MSC Mod Loader Pro Contributor Agreement
You, the contributor, grant us permission to use your code in any fashion in the scope of MSC Mod Loader Pro project.
While you get credited for your work, you may not demand any additional rights or obligations to your contribution.
To signify Agreement, Check the box below and type your (user)name.
[x] Tresquel

**Comment by Athlon007** [comment]
@cla-bot[bot] check

**Review by Athlon007 — APPROVED** [review]

**Comment by Athlon007** [comment]
Thank you for your contribution!

**Comment by Athlon007** [comment]
Merged in #28. Closing.

**Comment by Tresquel** [comment]
You haven't merged it yet

**Pull request closed without merging**
