### PR TITLE
Fix missing downloads folder exception

### LINKED ISSUE #24: System.IO.DirectoryNotFoundException: Downloads folder doesn't exist!
New to MSCModLoaderPro.
Issue occurs after MLP detects an available update, shuts itself down and launches CoolUpdater. 
Log attached.

Full message:
**```
(0s) Mod Loader Pro Auto-Update Tool Initialized!

System.IO.DirectoryNotFoundException: Downloads folder doesn't exist!
   bij CoolUpdater.UpdateView.<UpdateAll>d__18.MoveNext()
```**

Updates are not installed. Upon launching MSC, the issue persists and a loop is created.
Paths
Game Folder: D:\Steam\steamapps\common\My Summer Car
Mods Folder: D:\Steam\steamapps\common\My Summer Car\Mods
Save Folder: C:\Users\myusername\AppData\LocalLow\Amistech\My Summer Car

[log.txt](https://github.com/MSCLoaderPro/MSCModLoaderPro/files/6673446/log.txt)

### PR DESCRIPTION
**Pull request by Tresquel**
Should fix #24

### CODE REVIEW

**Comment by Tresquel** [comment]
MSC Mod Loader Pro Contributor Agreement

    You, the contributor, grant us permission to use your code in any fashion in the scope of MSC Mod Loader Pro project.
    While you get credited for your work, you may not demand any additional rights or obligations to your contribution.
    To signify Agreement, Check the box below and type your (user)name.

[x] Tresquel

**Comment by Athlon007** [comment]
@cla-bot[bot] check

**Review by Athlon007 — APPROVED** [review]

**Comment by Athlon007** [comment]
Merged in #30. Closing.

**Comment by Tresquel** [comment]
you havent merged it yet

**Pull request closed without merging**
